import type { Metadata } from "next";
import "./globals.css";
import {WrapFunction} from '@/context/userContext'

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <WrapFunction>
    <html lang="en">
      <body>
        {children}
      </body>
    </html>
    </WrapFunction>
  );
}
